sudo: false
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "3.6"

env:
    matrix:
        - TESTENV=py26
        - TESTENV=py27
        - TESTENV=py33
        - TESTENV=py34
        - TESTENV=py35
        - TESTENV=py36
        - TESTENV=pypy
        - TESTENV=pypy3

install:
  - pip install tox

script: tox -e $TESTENV

after_success:
    - bash <(curl -s https://codecov.io/bash)
